# Generated by Django 3.2.8 on 2021-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=32, verbose_name='사용자 비밀번호')),
            ],
        ),
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
