# Generated by Django 3.2.8 on 2021-11-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211107_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
