# Generated by Django 3.2.8 on 2021-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyList',
        ),
    ]
