# Generated by Django 3.2.8 on 2021-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmpapp', '0002_delete_companylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=100)),
                ('cmp_inderstry', models.CharField(max_length=100)),
                ('cmp_sales', models.CharField(max_length=100)),
                ('cmp_workers', models.IntegerField()),
                ('cmp_explanations', models.TextField()),
            ],
        ),
    ]
