# Generated by Django 3.2.8 on 2021-10-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapp', '0004_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyESG',
        ),
    ]
