# Generated by Django 3.2.8 on 2021-10-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapp', '0005_rename_company_companyesg'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyesg',
            name='ESG',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmpapp.companylist'),
        ),
    ]
