# Generated by Django 3.2.8 on 2021-10-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmpapp', '0007_rename_esg_companyesg_esg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyesg',
            name='esg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmpapp.companylist'),
        ),
    ]
