# Generated by Django 3.2.8 on 2021-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_choice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_count', models.IntegerField()),
                ('drink_amount', models.IntegerField()),
                ('smoke_yn', models.IntegerField()),
                ('smoke_amount', models.IntegerField()),
                ('exercise_count', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('family_stroke', models.IntegerField()),
                ('family_highBlood', models.IntegerField()),
                ('family_diabetes', models.IntegerField()),
                ('family_etc', models.IntegerField()),
            ],
        ),
    ]
