# Generated by Django 3.2.8 on 2021-11-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_producer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
