# Generated by Django 3.2.8 on 2021-11-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211107_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=1, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('남', '남자'), ('여', '여자')], max_length=1, verbose_name='성별'),
        ),
    ]
