# Generated by Django 3.2.8 on 2021-11-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211107_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(max_length=2, verbose_name='나이'),
        ),
    ]
